# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml
image: "rust:latest"

before_script:
   - apt-get update -yqq
   - apt-get install -yqq --no-install-recommends libclang-dev build-essential libtesseract-dev xorg-dev libwayland-dev libwayland-egl1 libegl1-mesa-dev libpipewire-0.3-dev libgbm-dev jq

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - ./update.sh
    - cargo test --workspace --verbose

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
